### ISSUE TITLE
Retrofit.java line 454

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#11]
#### in retrofit2.Retrofit$Builder.baseUrl

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b71d9606007d59fcdb17737?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b71d9606007d59fcdb17737?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Test app from makeroid
