### ISSUE TITLE
VerticalScrollHandler.java line 123

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#1125]
#### in cn.colintree.aix.ScrollArrangementHandlers.VerticalScrollHandler$2.onMove

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b914e1f6007d59fcde4e3fe?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b914e1f6007d59fcde4e3fe?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fatal Exception: java.lang.IllegalArgumentExceptionpointerIndex out of range Raw Text
--
  | android.view.MotionEvent.nativeGetAxisValue (MotionEvent.java)
  | android.view.MotionEvent.getY (MotionEvent.java:2233)
  | cn.colintree.aix.ScrollArrangementHandlers.VerticalScrollHandler$2.onMove (VerticalScrollHandler.java:123)
  | cn.colintree.aix.ScrollArrangementHandlers.VerticalScrollHandler$2.onTouch (VerticalScrollHandler.java:105)
