### ISSUE TITLE
com.google.appinventor.components.runtime.Surface.onPreviewFrame (Surface.java:215)

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#1134]
#### in android.hardware.Camera.native_getParameters

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b9162886007d59fcde696c7?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b9162886007d59fcde696c7?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by Sander0542** [comment]
android.hardware.Camera.native_getParameters (Camera.java)
--
  | android.hardware.Camera.getParameters (Camera.java:3078)
  | com.google.appinventor.components.runtime.Surface.onPreviewFrame (Surface.java:215)
  | android.hardware.Camera$EventHandler.handleMessage (Camera.java:1266)
  | android.os.Handler.dispatchMessage (Handler.java:111)
  | android.os.Looper.loop (Looper.java:207)
  | android.app.ActivityThread.main (ActivityThread.java:5742)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)
