### ISSUE TITLE
Network component

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#114]
#### in com.apptracker.android.track.AppTracker.isInternetAvailable

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b749e1f6007d59fcde48b4a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b749e1f6007d59fcde48b4a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fixed in master
