### ISSUE TITLE
register.yail line 10098

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#1174]
#### in io.makeroid.space_ravimishra.Quick_Cash.register.processException

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b92fd8f6007d59fcd0457f5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b92fd8f6007d59fcd0457f5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
fixed for next release
