### ISSUE TITLE
getMakeroidPackageName() - form.java

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#118]
#### in mt.b

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74cd796007d59fcde72e31?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74cd796007d59fcde72e31?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fixed in master
https://github.com/Sander0542/Makeroid/commit/dc19386145716f1b8d1ed1534f61ca98b5700db0
