### ISSUE TITLE
ViewMatchers.java line 11

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#122]
#### in androidx.test.espresso.matcher.ViewMatchers$WithEffectiveVisibilityMatcher.matchesSafely

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74fb6e6007d59fcde9e823?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74fb6e6007d59fcde9e823?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

at androidx.test.espresso.matcher.ViewMatchers$WithEffectiveVisibilityMatcher.matchesSafely(ViewMatchers.java:11)

@Sander0542 
@pavi2410
