### ISSUE TITLE
ThreadedRenderer.java

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#127]
#### in android.view.ThreadedRenderer.nDeleteProxy

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7526736007d59fcdecc96a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7526736007d59fcdecc96a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
We can do nothing:
https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin
