### ISSUE TITLE
VMRuntime.java

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#13]
#### in dalvik.system.VMRuntime.newNonMovableArray

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b722cc96007d59fcdb66ac5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b722cc96007d59fcdb66ac5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Out of memory issue.
We can do nothing.
