### ISSUE TITLE
MqttTopic.java line 171

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#1341]
#### in org.eclipse.paho.client.mqttv3.MqttTopic.validate

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b98f4516007d59fcd711f31?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b98f4516007d59fcd711f31?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
`

Fatal Exception: java.lang.IllegalArgumentExceptionInvalid topic length, should be in range[1, 65535]! Raw Text
--
  | org.eclipse.paho.client.mqttv3.MqttTopic.validate (MqttTopic.java:171)
  | org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish (MqttAsyncClient.java:1124)
  | org.eclipse.paho.client.mqttv3.MqttClient.publish (MqttClient.java:492)
  | co.com.dendritas.MqttTCP.AndroidThingsMessagingService$3.run (AndroidThingsMessagingService.java:173)
  | android.os.Handler.handleCallback (Handler.java:739)
  | android.os.HandlerThread.run (HandlerThread.java:61)

`
