### ISSUE TITLE
ColorScreenshotManager.java line 158

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#1807]
#### in com.color.screenshot.ColorScreenshotManager.isLongshotMoveState

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5baa3bc0f8b88c29633ee7ac?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5baa3bc0f8b88c29633ee7ac?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke interface method 'boolean com.color.screenshot.IColorScreenshotManager.isLongshotMoveState()' on a null object reference Raw Text
--
  | com.color.screenshot.ColorScreenshotManager.isLongshotMoveState (ColorScreenshotManager.java:158)
  | android.view.ColorInjector$View.onAwakenScrollBars (ColorInjector.java:104)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:759)
