### ISSUE TITLE
FirebaseDB.java line 530

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#19]
#### in com.google.appinventor.components.runtime.FirebaseDB.DataChanged

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7247d66007d59fcdb7f40b?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7247d66007d59fcdb7f40b?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Never seen this error before.
I think the app user or app developer did something wrong.
```
Fatal Exception: com.google.appinventor.components.runtime.errors.YailRuntimeError: Value failed to convert from JSON.
       at com.google.appinventor.components.runtime.FirebaseDB.DataChanged(FirebaseDB.java:530)
       at com.google.appinventor.components.runtime.FirebaseDB$1$1.run(FirebaseDB.java:132)
```
