### ISSUE TITLE
FlipShare.java line 112

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#198]
#### in com.jerin.flipshare.FlipShare$1.onItemClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b76f1756007d59fcd1097a6?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b76f1756007d59fcd1097a6?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
`

Fatal Exception: java.lang.IndexOutOfBoundsExceptionInvalid index 4, size is 4 Raw Text
--
  | java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:260)
  | java.util.ArrayList.get (ArrayList.java:313)
  | com.jerin.flipshare.FlipShare$1.onItemClick (FlipShare.java:112)
  | me.wangyuwei.flipshare.FlipShareView.onTouchEvent (FlipShareView.java:521)

`
