### ISSUE TITLE
GenericProc.java line 122

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#27]
#### in gnu.expr.GenericProc.applyN

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7284a86007d59fcdbbd3ff?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7284a86007d59fcdbbd3ff?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.toString()' on a null object reference
```
