### ISSUE TITLE
l line 1369

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#33]
#### in com.apptracker.android.track.AppTracker.I

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72b2366007d59fcdbf953e?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72b2366007d59fcdbf953e?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Same issue like https://github.com/Makeroid/BugsTracker/issues/17

@conorshipp Dont forget to fix the leadbolt bug ("true")

**Comment by barreeeiroo** [comment]
Duplicated of #17
