### ISSUE TITLE
Notifier - bug

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#37]
#### in com.google.appinventor.components.runtime.Notifier.toastNow

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72bf786007d59fcdc0b257?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72bf786007d59fcdc0b257?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fixed in master
