### ISSUE TITLE
Sound.java line 277

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#462]
#### in com.google.appinventor.components.runtime.Sound.playAndCheckResult

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7c4bba6007d59fcd6e2c1d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7c4bba6007d59fcd6e2c1d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
should be fixed
