### ISSUE TITLE
MakeroidListViewImageText

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#50]
#### in android.support.v4.content.ContextCompat.getDrawable

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72ef876007d59fcdc54be1?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72ef876007d59fcdc54be1?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
@Sander0542 Please take a look again to your listview component.
Looks like it needs to much ram.

`       at com.google.appinventor.components.runtime.MakeroidListViewImageText$ListAdapter.onCreateViewHolder(MakeroidListViewImageText.java:230)
       at com.google.appinventor.components.runtime.MakeroidListViewImageText$ListAdapter.onCreateViewHolder(MakeroidListViewImageText.java:221)`

**Comment by Sander0542** [comment]
Someone tries to load an image of 67mb
