### ISSUE TITLE
Log.java

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#594]
#### in android.util.Log.println_native

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b802e3b6007d59fcdb63579?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b802e3b6007d59fcdb63579?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
fixed for next bugfix release
