### ISSUE TITLE
CircleImageView.java line 367

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#612]
#### in de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b8102636007d59fcdc32d10?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b8102636007d59fcdc32d10?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Any of the  users is coder with GOD level....
He wants to use a 17,36MB as circle image in side menu...
