### ISSUE TITLE
BluetoothPlus.java line 441

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#685]
#### in com.sanderjochems.BluetoothPlus.BluetoothPlus.stopListeningMyBluetooth

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b8368626007d59fcdea6374?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b8368626007d59fcdea6374?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fatal Exception: java.lang.RuntimeExceptionUnable to destroy activity {io.makeroid.alysson_cabral.CarroCentral/io.makeroid.alysson_cabral.CarroCentral.Screen1}: java.lang.IllegalArgumentException: Receiver not registered: com.sanderjochems.BluetoothPlus.BluetoothPlus$C01622@a43e679 Raw Text
--
  | android.app.ActivityThread.performDestroyActivity (ActivityThread.java:3706)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:698)

**Comment by Sander0542** [comment]
That's my extension. Its not supported anymore
