### ISSUE TITLE
UiAutomation.java line 971 - AndroidX

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#70]
#### in android.app.UiAutomation.throwIfNotConnectedLocked

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73aa996007d59fcdd1e732?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73aa996007d59fcdd1e732?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
@Sander0542 Is is your test ?

**Comment by Sander0542** [comment]
No, I dont have an S7
