### ISSUE TITLE
Scrmedic.yail line 10100

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#708]
#### in io.makeroid.andreirr_oliveira.Ekonam.Scrmedic.processException

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b84792a6007d59fcdfe33c9?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b84792a6007d59fcdfe33c9?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
not sure what the user did
