### ISSUE TITLE
ContainerHelpers.java line 32

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#709]
#### in android.util.ContainerHelpers.binarySearch

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b848f8b6007d59fcdff578a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b848f8b6007d59fcdff578a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
This crash is caused by a bug in the Android platform, which was fixed in OS versions > 5. 1. You don’t need to make any changes to your app.
