### ISSUE TITLE
ExoPlayer

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#72]
#### in com.google.android.gms.ads.exoplayer1.extractor.mp4.f.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73aee26007d59fcdd225fe?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73aee26007d59fcdd225fe?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Maybe a update for the exoplayer library is enough.
