### ISSUE TITLE
Missing wallpaper permission

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#723]
#### in android.os.Parcel.readException

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b8526446007d59fcd092c73?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b8526446007d59fcd092c73?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
fixed for next bugfix release
