### ISSUE TITLE
ExoPlayer

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#73]
#### in com.google.android.gms.ads.exoplayer1.upstream.b.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73aeee6007d59fcdd22698?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73aeee6007d59fcdd22698?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Duplicate of https://github.com/Makeroid/BugsTracker/issues/73
