### ISSUE TITLE
FirebaseDB.java line 509

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#79]
#### in com.google.appinventor.components.runtime.FirebaseDB.GotValue

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73c9bb6007d59fcdd3c6e8?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73c9bb6007d59fcdd3c6e8?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
https://github.com/Sander0542/Makeroid/blob/23aaaae87d6fad7bc45e0ccbe48cdd5f0768a734/appinventor/components/src/com/google/appinventor/components/runtime/FirebaseDB.java#L509

**Comment by michael-winkler** [comment]
Fixed in master https://github.com/Sander0542/Makeroid/commit/0980280cb765e9601a43d2af5187139f30002e44
