### ISSUE TITLE
Videoplayer

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#80]
#### in android.view.View.measure

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73e33a6007d59fcdd59465?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73e33a6007d59fcdd59465?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
https://github.com/mit-cml/appinventor-sources/issues/1335
