### ISSUE TITLE
PopField.java line 83

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#85]
#### in rb.popview.PopField$2$1.onAnimationEnd

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b740e376007d59fcdd8f64a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b740e376007d59fcdd8f64a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
We have no component which uses:
https://github.com/krishnarb3/Popview-Android
