### ISSUE TITLE
Surface

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#88]
#### in android.hardware.Camera.startPreview

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74229a6007d59fcddab5a5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74229a6007d59fcddab5a5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Will fix this soon

**Comment by michael-winkler** [comment]
Fixed in master
