### ISSUE TITLE
AdvancedLocationSensor.java line 70

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#91]
#### in com.ginsnic.AdvancedLocationSensor.AdvancedLocationSensor$MyLocationListener.<init>

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74387b6007d59fcddcb558?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b74387b6007d59fcddcb558?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Extension:
com.ginsnic.AdvancedLocationSensor.AdvancedLocationSensor

```

Caused by java.lang.SecurityException"gps" location provider requires ACCESS_FINE_LOCATION permission. Raw Text
--
  | android.os.Parcel.readException (Parcel.java:1684)
  | android.location.LocationManager.addNmeaListener (LocationManager.java:1867)
  | com.ginsnic.AdvancedLocationSensor.AdvancedLocationSensor$MyLocationListener.<init> (AdvancedLocationSensor.java:70)
  | com.ginsnic.AdvancedLocationSensor.AdvancedLocationSensor.<init> (AdvancedLocationSensor.java:342)


```
